### PR TITLE
update categories, add security apps

### PR DESCRIPTION
**Pull request by tedthqme**
Rename VPN to Security
Rename Audio/Podcasts to Multimedia
-#Video

#Security
+FreeOTP
+KeePassDroid
+Wi-Fi Privacy Police
Move Prey to category

Minor spelling and copyediting to readme

I tested it, but you may want to double check to see if I made any errors.

### CODE REVIEW

**Comment by repat** [comment]
Thanks!

Google Authenticator isn't proprietary though, afaik.-> https://github.com/google/google-authenticator

**Comment by tedthqme** [comment]
Older versions of Google Authenticator are of course open source, but newer versions such as the one in the Play Store are proprietary. https://f-droid.org/wiki/page/com.google.android.apps.authenticator2

**Comment by repat** [comment]
Nah, that's fine. I didn't know that.

**Comment by repat** [comment]
Thanks!

**Pull request merged**
