### PR TITLE
New and replacement apps for navigation and multimedia.

### PR DESCRIPTION
**Pull request by ghost**
**Multimedia**
Removed Music Player (unmaintained)
Removed Turtle Player (unmaintained)
Added Material Audiobook Player
Added NewPipe

**News Reader**
Removed Flym
Added spaRSS (current fork of Flym)

**Navigation**
Removed Navit (I've tried it and it's a bad experience, same with ZANavi a "friendlier" fork)
Added MAPS.ME
Added Transportr

**Office**
Removed OpenDocument Reader (unmaintained and obsoleted by Libreoffice)

Updated F-Droid icon
Updated Libre Office Viewer icon
Removed Flock icon

### CODE REVIEW

**Comment by twzkxkan** [comment]
ping @repat

**Comment by JeanFred** [comment]
Original author gone, so unlikely to be followed up on... Shall we close it, and get specific pull-requests for individual suggestions ?

**Comment by lbnpmxbe** [comment]
Why close it? Merge it or say whats wrong.

**Comment by repat** [comment]
This happens sometimes, people make pull requests and instantly delete their accounts.  I just didn't get around to look through all of these, quite busy at the moment

**Comment by JeanFred** [comment]
@lbnpmxbe I had assumed the PR had gone unmerged as too complex to review, I’m happy it got merged :) Thanks @repat !

**Comment by repat** [comment]
@JeanFred That wasn't exactly wrong. But I also didn't like that Navit got removed, gotta put that back sometime. The removal of old apps is not a problem, especially when they're not in the app store(s) anymore, but Navit is perfectly fine afaik.

**Comment by repat** [comment]
I just re-read the original PR post from whoever the ghost is, and (s)he thought Navit is a bad experience. I don't exactly remember who added it (maybe it was me and it was the only app at the time or so). I guess with maps.me and OsmAnd we have enough anyway.

**Pull request merged**
