### PR TITLE
Add Calendar section with three alternatives

### LINKED ISSUE #40: Calendar app
(Subset of #36 in a way).

I will submit a PR with an alternative for Calendar app. Any suggestions?
* Per #36, [Etar](https://f-droid.org/repository/browse/?fdid=ws.xsoh.etar) ?
* [Offline calendar](https://f-droid.org/repository/browse/?fdfilter=calendar&fdid=org.sufficientlysecure.localcalendar) ?
* [Standalone Calendar](https://f-droid.org/repository/browse/?fdfilter=calendar&fdid=org.sufficientlysecure.standalonecalendar&fdpage=2)

Thoughts? (I can make all three to get the ball rolling).

### PR DESCRIPTION
**Pull request by JeanFred**
Add three alternatives (with icons) to Google Calendar and S Planner:
Etar, Offline Calendar and Standalone Calendar

Closes #40

### CODE REVIEW

**Comment by JeanFred** [comment]
Thoughts @repat ? :)

**Comment by repat** [comment]
Looks good, thanks! I'm traveling at the moment and don't have time to look over it completely, I'll be back Monday night and put it in the calender

**Comment by JeanFred** [comment]
Gentle up :)

**Comment by repat** [comment]
Thanks!

**Comment by JeanFred** [comment]
Thanks for merging!

**Pull request merged**
