### PR TITLE
new apps

### PR DESCRIPTION
**Pull request by qopisbel**
Tried to pick only the best.

#Messenger
+Conversations

#Notes
+Writeily Pro

#File Manager
+Amaze File Manager

#Cloud
+DAVdroid
+Flock

#Office
+LibreOffice Viewer
+Document Viewer
-VuDroid

#Misc
+QuickLyric
+Mitzuli

### CODE REVIEW

**Comment by qopisbel** [comment]
hold on the images didn't get pushed

**Comment by repat** [comment]
I don't exactly know why I can't merge that automatically but I'll find a way..

**Comment by qopisbel** [comment]
Sorry, I should have said to merge this one first.

**Comment by qopisbel** [comment]
Should be good to go now.

**Comment by repat** [comment]
thanks!

**Pull request merged**
